/* eslint-disable sonarjs/no-duplicate-string */
/* eslint-disable @typescript-eslint/naming-convention */

import { TechmmunitySectorEnum } from "core/enums/techmmunity-sector";

export const Interests = [
	/**
	 * Programming
	 */

	{
		name: "JavaScript",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: [
			"Programming Language",
			"JavaScript",
			"BackEnd",
			"FrontEnd",
			"Web",
			"Mobile",
		],
	},
	{
		name: "TypeScript",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: [
			"Programming Language",
			"JavaScript",
			"BackEnd",
			"FrontEnd",
			"Web",
			"Mobile",
		],
	},
	{
		name: "Flutter",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Language", "Mobile", "Web"],
	},
	{
		name: "Java",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Language", "BackEnd"],
	},
	{
		name: "NestJs",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Framework", "JavaScript", "BackEnd", "Api"],
	},
	{
		name: "NextJs",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Framework", "JavaScript", "FrontEnd"],
	},
	{
		name: "Spring Boot",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Framework", "BackEnd"],
	},
	{
		name: "TypeORM",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Node Library", "BackEnd", "ORM"],
	},
	{
		name: "Mongoose",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Node Library", "BackEnd", "ORM"],
	},
	{
		name: "Sequelize",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Node Library", "BackEnd", "ORM"],
	},
	{
		name: "Rust",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Language", "BackEnd"],
	},
	{
		name: "Python",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Language", "Machine Learning", "BackEnd"],
	},
	{
		name: "Django",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Python", "Framework", "BackEnd", "Api"],
	},
	{
		name: "Flask",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Python", "Framework", "BackEnd", "Api"],
	},
	{
		name: "PyGame",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Python", "Framework", "Game"],
	},
	{
		name: "FastAPI",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Python", "Framework", "BackEnd", "Api"],
	},
	{
		name: "Serverless Framework",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Framework", "Infrastructure", "Cloud", "CI"],
	},
	{
		name: "React",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Framework", "FrontEnd", "JavaScript"],
	},
	{
		name: "Angular",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Framework", "FrontEnd", "JavaScript", "React"],
	},
	{
		name: "Styled Components",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Library", "FrontEnd", "JavaScript", "React"],
	},
	{
		name: "SCSS / SASS",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["CSS", "FrontEnd"],
	},
	{
		name: "Vue",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Framework", "FrontEnd", "JavaScript"],
	},
	{
		name: "React Native",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Framework", "Mobile", "JavaScript"],
	},
	{
		name: "Expo",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Framework", "Mobile", "JavaScript", "React Native"],
	},
	{
		name: "C#",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Language", "BackEnd", "Desktop", "Mobile", "Game"],
	},
	{
		name: "Lua",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Language", "Game"],
	},
	{
		name: "Kotlin",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Language", "Mobile"],
	},
	{
		name: "PHP",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Language", "BackEnd"],
	},
	{
		name: "Word Press",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Tool", "BackEnd", "FrontEnd"],
	},
	{
		name: "Laravel",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Framework", "BackEnd", "PHP"],
	},
	{
		name: "Ruby",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Language", "BackEnd"],
	},
	{
		name: "Ruby On Rails",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Framework", "BackEnd", "Ruby"],
	},
	{
		name: "NodeJs",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Language", "BackEnd", "JavaScript"],
	},
	{
		name: "GraphQL",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["BackEnd"],
	},
	{
		name: "Elastic Search",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Database", "Indexing", "Elastic Stack"],
	},
	{
		name: "Elastic Stack",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Elastic Stack"],
	},
	{
		name: "Redis",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Database"],
	},
	{
		name: "AWS Stack",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Infrastructure", "Cloud", "Database"],
	},
	{
		name: "DynamoDB",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Database", "NoSQL"],
	},
	{
		name: "MongoDB",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Database", "NoSQL"],
	},
	{
		name: "PostgreSQL",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Database", "SQL"],
	},
	{
		name: "SQL Database Modeling",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Database", "SQL"],
	},
	{
		name: "NoSQL Database Modeling",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Database", "NoSQL"],
	},
	{
		name: "NPM Library Creation",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["JavaScript", "Library"],
	},
	{
		name: "Machine Learning",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Python", "AI", "IOT"],
	},
	{
		name: "Basic HTML & CSS",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["FrontEnd"],
	},
	{
		name: "Docker",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Infrastructure"],
	},
	{
		name: "Kubernetes",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Infrastructure", "CI"],
	},
	{
		name: "GitHub Actions",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Infrastructure", "CI"],
	},
	{
		name: "GitLab CI",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Infrastructure", "CI"],
	},
	{
		name: "Jenkins",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Infrastructure", "CI"],
	},
	{
		name: "SonarQube",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Code Quality", "Programming Tool"],
	},
	{
		name: "Fortify",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Code Security", "Programming Tool"],
	},
	{
		name: "Clean Arch",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Architecture", "Design Patterns"],
	},
	{
		name: "Hexagonal Arch",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Architecture", "Design Patterns"],
	},
	{
		name: "Onion Arch",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Architecture", "Design Patterns"],
	},
	{
		name: "Test Driven Development (TDD)",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Development Process"],
	},
	{
		name: "GCP",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Infrastructure", "Cloud"],
	},
	{
		name: "Azure",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Infrastructure", "Cloud"],
	},
	{
		name: "Golang",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programing Language"],
	},
	{
		name: "SEO Programming",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["SEO", "Programming Concept", "FrontEnd"],
	},
	{
		name: "Object Oriented Programming (OOP)",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Concept"],
	},
	{
		name: "Functional Oriented Programming (FOP)",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Concept"],
	},
	{
		name: "Micro-Services",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Concept", "BackEnd Structure"],
	},
	{
		name: "Serverless",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Concept", "BackEnd Structure"],
	},
	{
		name: "Micro-FrontEnd",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Concept", "FrontEnd Structure"],
	},
	{
		name: "Bash",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["Programming Language", "Script"],
	},
	{
		name: "Accessibility",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["FrontEnd"],
	},
	{
		name: "Responsive WebSite",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.PROGRAMMING,
		tags: ["FrontEnd"],
	},

	/**
	 * Graphic Design
	 */

	{
		name: "Figma",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.GRAPHIC_DESIGN,
		tags: ["Graphic Design Tool", "Mobile Design", "Web Design"],
	},
	{
		name: "Web Design",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.GRAPHIC_DESIGN,
		tags: [],
	},
	{
		name: "Mobile Design",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.GRAPHIC_DESIGN,
		tags: [],
	},
	{
		name: "Blender",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.GRAPHIC_DESIGN,
		tags: ["Graphic Design Tool", "3D Sculpting"],
	},
	{
		name: "Sony Vegas",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.GRAPHIC_DESIGN,
		tags: ["Graphic Design Tool", "Video Edition"],
	},
	{
		name: "Adobe Photoshop",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.GRAPHIC_DESIGN,
		tags: ["Graphic Design Tool", "Photo Edition", "Adobe"],
	},
	{
		name: "Adobe Illustrator",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.GRAPHIC_DESIGN,
		tags: ["Graphic Design Tool", "Adobe"],
	},
	{
		name: "Adobe After Effects",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.GRAPHIC_DESIGN,
		tags: ["Graphic Design Tool", "Adobe"],
	},
	{
		name: "Adobe Stack",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.GRAPHIC_DESIGN,
		tags: ["Graphic Design Tool", "Adobe"],
	},

	/**
	 * Robotic Engineering
	 */

	{
		name: "Arduino",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.ROBOTIC_ENGINEERING,
		tags: ["Hardware"],
	},
	{
		name: "RaspberryPi",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.ROBOTIC_ENGINEERING,
		tags: ["Hardware"],
	},

	/**
	 * Management
	 */

	{
		name: "Miro",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MANAGEMENT,
		tags: ["Management Tool"],
	},
	{
		name: "Power BI",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MANAGEMENT,
		tags: ["Management Tool"],
	},
	{
		name: "Jira",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MANAGEMENT,
		tags: ["Management Tool", "SCRUM"],
	},
	{
		name: "SCRUM",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MANAGEMENT,
		tags: ["Agile Methodology"],
	},
	{
		name: "Kanban",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MANAGEMENT,
		tags: ["Agile Methodology"],
	},
	{
		name: "Linkedin Recruting",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MANAGEMENT,
		tags: ["Soft Skill"],
	},
	{
		name: "Onboarding",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MANAGEMENT,
		tags: ["Soft Skill"],
	},
	{
		name: "Leadership",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MANAGEMENT,
		tags: ["Soft Skill"],
	},

	/**
	 * Marketing
	 */

	{
		name: "Google Analytics",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MARKETING,
		tags: ["Analytics"],
	},
	{
		name: "Facebook Pixel",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MARKETING,
		tags: ["Analytics"],
	},
	{
		name: "Google Ads",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MARKETING,
		tags: ["Announcement"],
	},
	{
		name: "Google Trends",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MARKETING,
		tags: ["Analytics"],
	},
	{
		name: "SEO Writing",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MARKETING,
		tags: ["SEO"],
	},
	{
		name: "Persona Definition",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MARKETING,
		tags: ["Target Audience"],
	},
	{
		name: "Target Audience",
		image: "",
		color: "",
		sector: TechmmunitySectorEnum.MARKETING,
		tags: ["Target Audience"],
	},
];
