import { getValues } from "./helpers/get-values";

export enum HeadlineEnum {
	CTO = "CTO",
	TECH_MANAGER = "TECH_MANAGER",
	TECH_LEADER = "TECH_LEADER",
	FULL_STACK_DEV = "FULL_STACK_DEV",
	FRONT_END_DEV = "FRONT_END_DEV",
	BACK_END_DEV = "BACK_END_DEV",
	GAME_DEV = "GAME_DEV",
	DESIGNER = "DESIGNER",
	GAME_DESIGNER = "GAME_DESIGNER",
	QUALITY_ASSURANCE = "QUALITY_ASSURANCE",
	ANIMATOR = "ANIMATOR",
	RECRUITER = "RECRUITER",
	SOCIAL_MEDIA = "SOCIAL_MEDIA",
}

export const HeadlineValues = () => getValues(HeadlineEnum);
