export enum PermissionsEnum {
	/**
	 * Articles
	 */
	ARTICLE_CREATE = "ARTICLE_CREATE",
	ARTICLE_UPDATE_OWN = "ARTICLE_UPDATE_OWN",
	ARTICLE_UPDATE_ALL = "ARTICLE_UPDATE_ALL",
	ARTICLE_DELETE_OWN = "ARTICLE_DELETE_OWN",
	ARTICLE_DELETE_ALL = "ARTICLE_DELETE_ALL",
	/**
	 * Article Question
	 */
	ARTICLE_QUESTION_CREATE = "ARTICLE_QUESTION_CREATE",
	ARTICLE_QUESTION_UPDATE_OWN = "ARTICLE_QUESTION_UPDATE_OWN",
	ARTICLE_QUESTION_UPDATE_ALL = "ARTICLE_QUESTION_UPDATE_ALL",
	ARTICLE_QUESTION_DELETE_OWN = "ARTICLE_QUESTION_DELETE_OWN",
	ARTICLE_QUESTION_DELETE_ALL = "ARTICLE_QUESTION_DELETE_ALL",
	/**
	 * Article Answer
	 */
	ARTICLE_ANSWER_CREATE = "ARTICLE_ANSWER_CREATE",
	ARTICLE_ANSWER_UPDATE_OWN = "ARTICLE_ANSWER_UPDATE_OWN",
	ARTICLE_ANSWER_UPDATE_ALL = "ARTICLE_ANSWER_UPDATE_ALL",
	ARTICLE_ANSWER_DELETE_OWN = "ARTICLE_ANSWER_DELETE_OWN",
	ARTICLE_ANSWER_DELETE_ALL = "ARTICLE_ANSWER_DELETE_ALL",
	/**
	 * Forum Question
	 */
	FORUM_QUESTION_CREATE = "FORUM_QUESTION_CREATE",
	FORUM_QUESTION_UPDATE_OWN = "FORUM_QUESTION_UPDATE_OWN",
	FORUM_QUESTION_UPDATE_ALL = "FORUM_QUESTION_UPDATE_ALL",
	FORUM_QUESTION_DELETE_OWN = "FORUM_QUESTION_DELETE_OWN",
	FORUM_QUESTION_DELETE_ALL = "FORUM_QUESTION_DELETE_ALL",
	/**
	 * Forum Answer
	 */
	FORUM_ANSWER_CREATE = "FORUM_ANSWER_CREATE",
	FORUM_ANSWER_UPDATE_OWN = "FORUM_ANSWER_UPDATE_OWN",
	FORUM_ANSWER_UPDATE_ALL = "FORUM_ANSWER_UPDATE_ALL",
	FORUM_ANSWER_DELETE_OWN = "FORUM_ANSWER_DELETE_OWN",
	FORUM_ANSWER_DELETE_ALL = "FORUM_ANSWER_DELETE_ALL",
	/**
	 * Courses
	 */
	COURSE_CREATE = "COURSE_CREATE",
	COURSE_UPDATE_OWN = "COURSE_UPDATE_OWN",
	COURSE_UPDATE_ALL = "COURSE_UPDATE_ALL",
	COURSE_DELETE_OWN = "COURSE_DELETE_OWN",
	COURSE_DELETE_ALL = "COURSE_DELETE_ALL",
	/**
	 * Certification
	 */
	CERTIFICATION_BUY = "CERTIFICATION_BUY",
	CERTIFICATION_SELL = "CERTIFICATION_SELL",
	/**
	 * Project
	 */
	PROJECT_CREATE = "PROJECT_CREATE",
	PROJECT_UPDATE_OWN = "PROJECT_UPDATE_OWN",
	PROJECT_UPDATE_ALL = "PROJECT_UPDATE_ALL",
	/**
	 * Mentoring
	 */
	MENTOR_ADD = "MENTOR_ADD",
	MENTOR_REMOVE = "MENTOR_REMOVE",
}
